"""Load and derive the leaf gas-exchange data used for manuscript section 2.4.

The derived results generated by this module were subsequently incorporated
into the manuscript.

The raw workbook holds one row per leaf measurement. Recorded directly: net CO2
assimilation ``A``, stomatal conductance ``gs``, transpiration ``E``, incident
``PPFD``, leaf and air temperature. Derived here: the three efficiency ratios and
the leaf-to-air temperature difference.

Apparent quantum yield (``Phi``) is not a per-leaf value -- it is the slope of A
against PPFD at low light, so it is estimated per group and compared between
sexes by ANCOVA rather than by t-test.
"""
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
from scipy.stats import linregress

# Imported as `cfg`, not `C`: patsy resolves the categorical marker C() from this
# module's namespace, so binding C to the config module would break the formulas.
from . import config as cfg

SEASON_ORDER = ["primavera", "verao", "outono", "inverno"]
SEASON_LABELS = {"primavera": "Spring", "verao": "Summer",
                 "outono": "Autumn", "inverno": "Winter"}
LEAF_AGE_ORDER = ["Jovem", "Jov_Madura", "Madura", "Velha"]

SYSTEM_LABEL = {"MO": "MO", "FUS": "AFS"}


def load_physiology():
    """Return the cleaned gas-exchange frame with derived traits."""
    df = pd.read_excel(cfg.RAW_PHYSIO, sheet_name="folhas")

    # 'sol' = monoculture, 'sombra' = agroforestry.
    df["environment"] = df["Tipo"].map({"sol": "MO", "sombra": "FUS"})
    df["period_label"] = df["Ep_Medicao"].map(cfg.EP_TO_PERIOD)
    df["Estacoes"] = pd.Categorical(df["Estacoes"], categories=SEASON_ORDER, ordered=True)
    df["IdadeE"] = pd.Categorical(df["IdadeE"], categories=LEAF_AGE_ORDER, ordered=True)

    # Ratios are undefined or meaningless where the denominator is zero/negative
    # or where the leaf sat in near-darkness, so those records are masked out.
    valid = (df["A"] > 0) & (df["E"] > 0) & (df["gs"] > 0) & (df["PPFD"] > 1)
    df["WUE"] = np.where(valid, df["A"] / df["E"], np.nan)
    df["iWUE"] = np.where(valid, df["A"] / df["gs"], np.nan)
    df["LUE"] = np.where(valid, df["A"] / df["PPFD"], np.nan)
    df["deltaT"] = df["Tl"] - df["Ta"]

    df["bio_unit"] = df["Planta"].astype(str) + "_" + df["Ep_Emissao"].astype(str)
    df["time_idx"] = df["period_label"].map(cfg.PERIOD_TO_TIDX)
    return df


def apparent_quantum_yield(sub):
    """Slope of A against PPFD for one group (records with A > 0 and PPFD > 5)."""
    lr = sub[(sub["A"] > 0) & (sub["PPFD"] > 5)]
    if len(lr) < 3 or (lr["PPFD"].max() - lr["PPFD"].min()) <= 50:
        return np.nan
    return linregress(lr["PPFD"], lr["A"]).slope


def aqy_by_sex(sub):
    """Female and male A-vs-PPFD slopes plus the ANCOVA slope-difference p-value."""
    lr = sub[(sub["A"] > 0) & (sub["PPFD"] > 5)]
    slope_f = linregress(lr[lr.Sexo == "F"].PPFD, lr[lr.Sexo == "F"].A).slope
    slope_m = linregress(lr[lr.Sexo == "M"].PPFD, lr[lr.Sexo == "M"].A).slope
    p = smf.ols("A ~ PPFD*C(Sexo)", data=lr).fit().pvalues.get("PPFD:C(Sexo)[T.M]", np.nan)
    return {"F": slope_f, "M": slope_m, "p": float(p),
            "n_F": int((lr.Sexo == "F").sum()), "n_M": int((lr.Sexo == "M").sum())}


def attach_environment(physio, unified):
    """Join the midday environmental drivers of each campaign onto every leaf record."""
    lookup = (unified.groupby(["environment", "time_idx"])[cfg.PHYSIO_ENV_FEATURES]
                     .first().reset_index())
    out = physio.merge(lookup, on=["environment", "time_idx"], how="left")
    return out.dropna(subset=cfg.PHYSIO_ENV_FEATURES)
